name: Build & Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn run build:full

      - uses: chrislennon/action-aws-cli@v1.1
      - name: Deploy
        run: |
          node jobs/upload-ipfs.js
          aws s3 sync ./dist/gnosis-app/ s3://gnosis.1inch.exchange --delete --exact-timestamps
          aws s3 sync ./dist/gnosis-app/ s3://gnosis.1inch.exchange --delete --exact-timestamps
          aws s3 sync ./dist/gnosis-app/ s3://gnosis.1inch.exchange --delete --exact-timestamps
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          IPFS_AUTHORIZATION: ${{ secrets.IPFS_AUTHORIZATION }}
